/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campaigns
         * @description Return one summary per folder under campaigns_dir that has a config.
         *
         *     Folders without ``campaign_config.json`` are silently skipped — the
         *     UI only renders runnable campaigns. Invalid configs are also skipped
         *     (logged at WARN) so a single broken JSON file can't 500 the list.
         */
        get: operations["list_campaigns_api_v1_campaigns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Campaign
         * @description Return full detail (summary + history) for a single campaign.
         */
        get: operations["get_campaign_api_v1_campaigns__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{name}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Campaign
         * @description Spawn ``scripts.publish_campaign`` as a detached subprocess.
         *
         *     Fire-and-forget by design: the publisher writes to ``state.json`` and
         *     the frontend polls ``GET /campaigns``. Lock conflicts surface there
         *     as ``last_status="error"`` on the next poll, identical to the cron
         *     path. Returns immediately with the spawned PID.
         */
        post: operations["publish_campaign_api_v1_campaigns__name__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/recipe-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recipe Card Webhook
         * @description Accept a WordPress publish event and queue PDF generation.
         */
        post: operations["recipe_card_webhook_api_v1_webhooks_recipe_card_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recipes
         * @description List stored recipes (alphabetical) with optional filters.
         */
        get: operations["list_recipes_api_v1_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recipes Analytics
         * @description Aggregated publish outcomes across all recipes (phase 10, local log).
         */
        get: operations["recipes_analytics_api_v1_recipes_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Recipe
         * @description Promote a pending recipe to approved (the human gate, phase 5).
         */
        post: operations["approve_recipe_api_v1_recipes__recipe_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Recipe
         * @description Reject a pending recipe so it is never published (phase 5).
         */
        post: operations["reject_recipe_api_v1_recipes__recipe_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recipe
         * @description Full detail for one recipe, including ingredients and steps.
         */
        get: operations["get_recipe_api_v1_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recipe Page
         * @description Render the recipe as a standalone HTML page (DB fields + image artifacts).
         *
         *     Image refs point at the artifact endpoint so photos resolve inside an
         *     ``<iframe>`` preview. Re-rendered per call to reflect current DB state — the
         *     same markup the publisher emits, viewable before anything goes live.
         */
        get: operations["recipe_page_api_v1_recipes__recipe_id__page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/image-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recipe Image Preview
         * @description Render the post_image.html recipe card with base64-embedded assets.
         *
         *     The card shows: food photo | dog avatar | recipe name | ingredients | timing.
         *     All assets are inlined as base64 data URIs so the page is fully self-contained.
         *     Returns a green placeholder when ``post_image.jpg`` has not yet been generated.
         */
        get: operations["recipe_image_preview_api_v1_recipes__recipe_id__image_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/sync-publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Publish
         * @description Refresh each recipe's publish status from the publish records.
         *
         *     Reads the brand's ``campaigns/**\/metadata.json`` and
         *     ``published_recipes.json`` and writes per-channel status onto matching
         *     recipe rows. Idempotent and safe to call repeatedly.
         */
        post: operations["sync_publish_api_v1_recipes_sync_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description List every file in the recipe's artifact folder, for the UI viewer.
         */
        get: operations["list_artifacts_api_v1_recipes__recipe_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Serve a single artifact file (path-traversal guarded).
         */
        get: operations["get_artifact_api_v1_recipes__recipe_id__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/media-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media File
         * @description Serve a media file referenced by a recipe's media manifest.
         *
         *     Paths are BRAND_DIR-relative and may live under either the live
         *     ``recipe_artifacts`` folder or the ``_migrated_backup`` folder, so this
         *     guards to *both* of the recipe's own media dirs (path-traversal safe) rather
         *     than the single artifacts dir used by ``get_artifact``.
         */
        get: operations["get_media_file_api_v1_recipes__recipe_id__media_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/story-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Card
         * @description Generate and return a story card JPEG for the given recipe.
         */
        get: operations["get_story_card_api_v1_recipes__recipe_id__story_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engagements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Engagements Endpoint
         * @description Most-recent-first published posts/comments, optionally filtered, plus counts.
         */
        get: operations["list_engagements_endpoint_api_v1_engagements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ideas
         * @description List content ideas, newest first. Defaults to all statuses.
         */
        get: operations["list_ideas_api_v1_ideas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ideas/{idea_id}/slides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Idea Slides
         * @description Return slide URLs for an idea's saved carousel (empty list if not generated yet).
         */
        get: operations["list_idea_slides_api_v1_ideas__idea_id__slides_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ideas/{idea_id}/slides/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Idea Slide
         * @description Serve a single carousel slide JPEG.
         */
        get: operations["get_idea_slide_api_v1_ideas__idea_id__slides__n__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ideas/{idea_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Idea Status
         * @description Update the status of a single idea.
         */
        patch: operations["update_idea_status_api_v1_ideas__idea_id__status_patch"];
        trace?: never;
    };
    "/api/v1/tiktok-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description List TikTok follow candidates.
         */
        get: operations["list_candidates_api_v1_tiktok_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tiktok-candidates/{handle}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Candidate Status
         * @description Update the status of a TikTok candidate.
         */
        patch: operations["update_candidate_status_api_v1_tiktok_candidates__handle__status_patch"];
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Returns the current site configuration.
         */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending
         * @description All blog-post pairs, group-join candidates, ideas, seeds, campaign-verify items, and comments awaiting a decision.
         */
        get: operations["list_pending_api_v1_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity
         * @description Tail of ``logs/engagement_log.jsonl``, most recent first.
         */
        get: operations["list_activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Look up a single item by id.
         */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Item
         * @description Approve an item. Dispatches on type.
         */
        post: operations["approve_item_api_v1_items__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Item
         * @description Reject an item. Dispatches on type. Logs ``body.reason`` (free-form).
         */
        post: operations["reject_item_api_v1_items__item_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Item
         * @description Approve with edited content. Only valid for blog_post items.
         */
        post: operations["edit_item_api_v1_items__item_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Facebook Groups
         * @description List all Facebook groups bucketed by status.
         *
         *     Merges two sources:
         *       - groups_tracker.json -> status in {joined, join_requested, rejected}
         *       - pending_groups.json -> projected with synthetic status="not_joined_yet"
         */
        get: operations["list_facebook_groups_api_v1_facebook_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/groups/{group_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Facebook Group
         * @description Update a Facebook group's status / posting_mode in the groups DB.
         */
        put: operations["update_facebook_group_api_v1_facebook_groups__group_name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for launchd / curl. 204 = OK, no body needed.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workers
         * @description List all scheduled workers with their last run status from DB.
         */
        get: operations["list_workers_api_v1_workers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{label}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Worker Status
         * @description Return the last run status for a single worker.
         */
        get: operations["worker_status_api_v1_workers__label__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{label}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Worker
         * @description Fire a scheduled worker on demand.
         *
         *     ``body.count`` (1–3) spawns that many parallel instances — useful once
         *     workers are backed by a Redis task queue so each instance independently
         *     pops and processes tasks.  Each instance gets its own PID file
         *     ``<suffix>_<i>.pid``.  If any slot is already occupied the whole
         *     request is rejected with 409.
         */
        post: operations["trigger_worker_api_v1_workers__label__trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Missing Flows
         * @description Return scheduled flows defined in schedule.json that aren't loaded in launchctl.
         */
        get: operations["list_missing_flows_api_v1_schedule_missing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{label}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Log
         * @description Return the last N lines of the log file for a scheduled job.
         */
        get: operations["get_schedule_log_api_v1_workers__label__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{label}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Artifact
         * @description Return the JSON content of the output_file for a scheduled job.
         */
        get: operations["get_schedule_artifact_api_v1_workers__label__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEntry
         * @description One row in ``logs/engagement_log.jsonl`` as exposed by ``/activity``.
         *
         *     Some legacy rows in the JSONL file use ``action="group_join_request"``;
         *     the API layer normalises those to ``"group_join"`` before constructing
         *     this model so the frontend only ever sees the canonical value. Older
         *     rows may also lack the ``date`` field — ``lib.activity_log`` derives
         *     it from ``timestamp`` so the UI can rely on both being present.
         */
        ActivityEntry: {
            /** Date */
            date: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Action
             * @enum {string}
             */
            action: "comment" | "like" | "group_post" | "reply" | "own_reply" | "page_post" | "feed_post" | "group_join" | "trace";
            /**
             * Platform
             * @enum {string}
             */
            platform: "facebook" | "instagram" | "wordpress" | "system";
            /** Target Name */
            target_name?: string | null;
            /** Target Url */
            target_url?: string | null;
            /** Content */
            content?: string | null;
            /** Reply Url */
            reply_url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ActivityResponse
         * @description Envelope for ``GET /api/v1/activity``.
         */
        ActivityResponse: {
            /** Entries */
            entries: components["schemas"]["ActivityEntry"][];
            /** Total */
            total: number;
            /** As Of */
            as_of: string;
        };
        /**
         * AffiliateProduct
         * @description One matched Amazon-Associates product (from the affiliate-matching phase).
         */
        AffiliateProduct: {
            /** Key */
            key: string;
            /** Asin */
            asin: string;
            /** Display */
            display: string;
        };
        /**
         * AnalyticsResponse
         * @description Aggregated publish outcomes (phase 10, local outcome log).
         */
        AnalyticsResponse: {
            /** Recipes */
            recipes: number;
            /** Attempts */
            attempts: number;
            /** By Platform */
            by_platform?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** By Status */
            by_status?: {
                [key: string]: number;
            };
        };
        /**
         * ApproveBody
         * @description Body for ``POST /items/{id}/approve``.
         *
         *     All fields optional: a bare approve just commits the existing draft.
         *     Pass ``text`` to override a comment, or ``fb_caption``/``ig_caption``
         *     to override a blog post pair before approval.
         */
        ApproveBody: {
            /** Text */
            text?: string | null;
            /** Fb Caption */
            fb_caption?: string | null;
            /** Ig Caption */
            ig_caption?: string | null;
        };
        /**
         * ArtifactItem
         * @description One file in a recipe's artifact folder, listed for the UI.
         */
        ArtifactItem: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Kind */
            kind: string;
            /**
             * Size
             * @default 0
             */
            size: number;
        };
        /**
         * ArtifactsResponse
         * @description Envelope for ``GET /api/v1/recipes/{id}/artifacts``.
         */
        ArtifactsResponse: {
            /** Recipe Id */
            recipe_id: string;
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactItem"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * BlogPostItem
         * @description A WordPress post awaiting FB + IG caption sign-off.
         *
         *     ``channel`` is the per-platform fan-out decision set by the approver:
         *
         *     - Web UI: ``POST /items/{id}/approve?channel=fb_only`` stamps this field
         *       before flipping ``status`` to ``approved``.
         *     - Telegram: the reply parser in ``lib/notifier.py`` maps text replies
         *       (``approve``/``fb``/``ig``) onto ``"both"``/``"fb_only"``/``"ig_only"``.
         *
         *     The publisher (``scripts/content_pipeline.py::stage_publish``) reads
         *     ``channel`` after ``send_and_wait`` returns to decide which platforms to
         *     actually post to. ``None`` is valid only while the item is still pending
         *     or was skipped.
         */
        BlogPostItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "blog_post";
            /**
             * Post Title
             * @default
             */
            post_title: string;
            /**
             * Post Url
             * @default
             */
            post_url: string;
            /**
             * Post Id
             * @default 0
             */
            post_id: number;
            /**
             * Fb Caption
             * @default
             */
            fb_caption: string;
            /**
             * Ig Caption
             * @default
             */
            ig_caption: string;
            /** Image Url */
            image_url?: string | null;
            /** Channel */
            channel?: ("both" | "fb_only" | "ig_only") | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CampaignDetail
         * @description Detail payload for ``GET /api/v1/campaigns/{name}``.
         *
         *     Extends ``CampaignSummary`` with the full run history list so the UI
         *     can render the timeline view without a second round-trip.
         */
        CampaignDetail: {
            /** Name */
            name: string;
            /** Last Run */
            last_run?: string | null;
            /**
             * Current Task Index
             * @default 0
             */
            current_task_index: number;
            /**
             * Last Status
             * @default never
             * @enum {string}
             */
            last_status: "success" | "error" | "never";
            /**
             * Ready Count
             * @default 0
             */
            ready_count: number;
            /**
             * Published Count
             * @default 0
             */
            published_count: number;
            /**
             * Has Prepare Tasks
             * @default false
             */
            has_prepare_tasks: boolean;
            /**
             * Has Publish Tasks
             * @default false
             */
            has_publish_tasks: boolean;
            /**
             * History
             * @default []
             */
            history: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CampaignListResponse
         * @description Envelope for ``GET /api/v1/campaigns``.
         */
        CampaignListResponse: {
            /** Campaigns */
            campaigns: components["schemas"]["CampaignSummary"][];
        };
        /**
         * CampaignSummary
         * @description Summary row for ``GET /api/v1/campaigns``.
         *
         *     Aggregates the on-disk campaign config + state.json + ready/published
         *     folder counts into a single UI-friendly shape. ``last_status`` is
         *     derived from ``state.history[-1].status`` and defaults to ``"never"``
         *     when the campaign has no run history yet.
         */
        CampaignSummary: {
            /** Name */
            name: string;
            /** Last Run */
            last_run?: string | null;
            /**
             * Current Task Index
             * @default 0
             */
            current_task_index: number;
            /**
             * Last Status
             * @default never
             * @enum {string}
             */
            last_status: "success" | "error" | "never";
            /**
             * Ready Count
             * @default 0
             */
            ready_count: number;
            /**
             * Published Count
             * @default 0
             */
            published_count: number;
            /**
             * Has Prepare Tasks
             * @default false
             */
            has_prepare_tasks: boolean;
            /**
             * Has Publish Tasks
             * @default false
             */
            has_publish_tasks: boolean;
        };
        /**
         * CampaignVerifyItem
         * @description A campaign awaiting final human verification before publish.
         */
        CampaignVerifyItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "campaign_verify";
            /**
             * Seed Id
             * @default
             */
            seed_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Wp Draft Url
             * @default
             */
            wp_draft_url: string;
            /** Audio Size Kb */
            audio_size_kb?: number | null;
            /** Slide Count */
            slide_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** CandidatesResponse */
        CandidatesResponse: {
            /** Candidates */
            candidates: components["schemas"]["TikTokCandidateItem"][];
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /**
         * CommentItem
         * @description A Facebook / Instagram / WordPress engagement comment.
         *
         *     Legacy schema — engagement comments no longer flow through the web UI,
         *     but the model is retained so the autonomous pipeline (comment_poster)
         *     and legacy items in ``comment_queue.json`` can still validate.
         */
        CommentItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "comment";
            /**
             * Platform
             * @enum {string}
             */
            platform: "facebook" | "instagram" | "wordpress" | "system";
            /** Group Or Hashtag */
            group_or_hashtag?: string | null;
            /** Post Url */
            post_url?: string | null;
            /**
             * Post Text
             * @default
             */
            post_text: string;
            /**
             * Draft Comment
             * @default
             */
            draft_comment: string;
            /** Relevance Score */
            relevance_score?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ContentIdea */
        ContentIdea: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Topic */
            topic: string;
            /** Target Keyword */
            target_keyword?: string | null;
            /** Nalla Context */
            nalla_context?: string | null;
            /** Post Goal */
            post_goal?: string | null;
            /** Status */
            status: string;
            /** Input */
            input?: string | null;
            /** Brand Id */
            brand_id?: string | null;
            /** Brand Name */
            brand_name?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * DecisionResponse
         * @description Returned on every commit endpoint.
         */
        DecisionResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /**
             * Decided By
             * @enum {string}
             */
            decided_by: "telegram" | "web_ui" | "auto";
            /** Decided At */
            decided_at: string;
            /** Join Status */
            join_status?: "queued" | null;
        };
        /**
         * EditBody
         * @description Body for ``POST /items/{id}/edit``.
         *
         *     Either ``text`` (comment items) or one/both of ``fb_caption`` /
         *     ``ig_caption`` (blog-post items) must be set — enforced in the route
         *     handler so the response is a clean 422 instead of an opaque ValidationError.
         */
        EditBody: {
            /** Text */
            text?: string | null;
            /** Fb Caption */
            fb_caption?: string | null;
            /** Ig Caption */
            ig_caption?: string | null;
        };
        /**
         * Engagement
         * @description One published post or comment.
         */
        Engagement: {
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /**
             * Target Name
             * @default
             */
            target_name: string;
            /**
             * Target Url
             * @default
             */
            target_url: string;
            /**
             * Permalink
             * @default
             */
            permalink: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Source Ref
             * @default
             */
            source_ref: string;
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Posted At
             * @default
             */
            posted_at: string;
        };
        /** EngagementsResponse */
        EngagementsResponse: {
            /** Engagements */
            engagements: components["schemas"]["Engagement"][];
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /**
         * FacebookGroup
         * @description A Facebook group from groups_tracker.json.
         */
        FacebookGroup: {
            /** Group Name */
            group_name: string;
            /** Group Url */
            group_url: string;
            /** Status */
            status: string;
            /** Joined At */
            joined_at?: string | null;
            /** Rules */
            rules?: string | null;
            /** Last Post At */
            last_post_at?: string | null;
            /** Source Notification */
            source_notification?: string | null;
            /** Privacy */
            privacy?: string | null;
            /** Member Count */
            member_count?: string | null;
            /** Posting Mode */
            posting_mode?: string | null;
            /** Notes */
            notes?: {
                [key: string]: string;
            }[] | null;
            /** Last Post Status */
            last_post_status?: string | null;
            /** Last Post Caption */
            last_post_caption?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FacebookGroupUpdateBody
         * @description Body for PUT /api/v1/facebook/groups/{group_name}.
         */
        FacebookGroupUpdateBody: {
            /** Status */
            status?: string | null;
            /** Posting Mode */
            posting_mode?: string | null;
        };
        /**
         * FacebookGroupsResponse
         * @description Envelope for GET /api/v1/facebook/groups.
         */
        FacebookGroupsResponse: {
            /** Groups */
            groups: components["schemas"]["FacebookGroup"][];
            /** Total */
            total: number;
            /** As Of */
            as_of: string;
        };
        /**
         * GroupItem
         * @description A Facebook group surfaced by ``fb_group_scout`` awaiting a join
         *     decision.
         *
         *     Producer side (``lib/group_discovery/state.py:add_to_pending``) writes
         *     the discovery payload without ``id``/``status``/``decided_by`` — the API
         *     layer synthesises those when reading (see ``lib/groups_queue.py``). The
         *     ``model_config = extra="allow"`` inherited from ``_ItemBase`` keeps the
         *     extra producer fields (``post_frequency``, ``competitor_names``,
         *     ``description``) intact for the UI even though they aren't declared.
         */
        GroupItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group_to_join";
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Member Count */
            member_count?: number | null;
            /** Score */
            score?: number | null;
            /** Privacy */
            privacy?: ("public" | "private") | null;
            /** Found Via Query */
            found_via_query?: string | null;
            /** Competitor Mentions */
            competitor_mentions?: number | null;
            /** Added To Pending */
            added_to_pending: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdeaItem
         * @description A recipe/content idea from the ideator queue awaiting approval.
         */
        IdeaItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "idea";
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Why Now
             * @default
             */
            why_now: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /** Seasonal Relevance */
            seasonal_relevance?: number | null;
            /**
             * Search Demand Estimate
             * @default
             */
            search_demand_estimate: string;
        } & {
            [key: string]: unknown;
        };
        /** IdeasResponse */
        IdeasResponse: {
            /** Ideas */
            ideas: components["schemas"]["ContentIdea"][];
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /**
         * LogTailResponse
         * @description Envelope for ``GET /api/v1/schedule/{label}/log``.
         */
        LogTailResponse: {
            /** Label */
            label: string;
            /** Path */
            path: string | null;
            /** Lines */
            lines: string[];
            /** Truncated */
            truncated: boolean;
        };
        /**
         * MissingFlowEntry
         * @description One scheduled flow that's defined in schedule.json but not loaded in launchctl.
         */
        MissingFlowEntry: {
            /** Label */
            label: string;
            /** Plist Path */
            plist_path?: string | null;
            /** Command */
            command: string;
        };
        /**
         * MissingFlowsResponse
         * @description Envelope for ``GET /api/v1/schedule/missing``.
         */
        MissingFlowsResponse: {
            /** Missing */
            missing: components["schemas"]["MissingFlowEntry"][];
            /** As Of */
            as_of: string;
        };
        /**
         * PendingResponse
         * @description Envelope for ``GET /api/v1/pending``.
         */
        PendingResponse: {
            /** Items */
            items: (components["schemas"]["CommentItem"] | components["schemas"]["BlogPostItem"] | components["schemas"]["GroupItem"] | components["schemas"]["IdeaItem"] | components["schemas"]["SeedItem"] | components["schemas"]["CampaignVerifyItem"])[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** As Of */
            as_of: string;
        };
        /**
         * PublishChannel
         * @description Publish state for one channel (wp / pdf / ig / fb).
         *
         *     IG-only extras (``caption`` / ``reel_url`` / ``post_url``) carry the
         *     Instagram single-image post + reel split surfaced in the UI popup. They
         *     stay empty for the other channels.
         */
        PublishChannel: {
            /**
             * State
             * @default
             */
            state: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Ref
             * @default
             */
            ref: string;
            /**
             * At
             * @default
             */
            at: string;
            /**
             * Caption
             * @default
             */
            caption: string;
            /**
             * Reel Url
             * @default
             */
            reel_url: string;
            /**
             * Post Url
             * @default
             */
            post_url: string;
        };
        /** RecipeCardWebhookPayload */
        RecipeCardWebhookPayload: {
            /** Post Id */
            post_id: number;
            /** Post Status */
            post_status: string;
            /**
             * Post Type
             * @default post
             */
            post_type: string;
        };
        /**
         * RecipeDetail
         * @description Full recipe payload for ``GET /api/v1/recipes/{id}``.
         */
        RecipeDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Artifacts Path
             * @default
             */
            artifacts_path: string;
            /**
             * Card Path
             * @default
             */
            card_path: string;
            /**
             * Card Created At
             * @default
             */
            card_created_at: string;
            /**
             * Card Html Path
             * @default
             */
            card_html_path: string;
            /**
             * Card Html Created At
             * @default
             */
            card_html_created_at: string;
            /**
             * Wp Url
             * @default
             */
            wp_url: string;
            /**
             * Ig Url
             * @default
             */
            ig_url: string;
            /**
             * Fb Url
             * @default
             */
            fb_url: string;
            /**
             * Published At
             * @default
             */
            published_at: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Dog Safe
             * @default false
             */
            dog_safe: boolean;
            /** Toxic Flags */
            toxic_flags?: string[];
            /** Season Tags */
            season_tags?: string[];
            /** Affiliate Products */
            affiliate_products?: components["schemas"]["AffiliateProduct"][];
            /**
             * Content Status
             * @default none
             */
            content_status: string;
            /** Status */
            status: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Source Name
             * @default
             */
            source_name: string;
            /**
             * Prep Minutes
             * @default 0
             */
            prep_minutes: number;
            /**
             * Cook Minutes
             * @default 0
             */
            cook_minutes: number;
            /**
             * Total Minutes
             * @default 0
             */
            total_minutes: number;
            /**
             * Servings
             * @default
             */
            servings: string;
            /** Publish Status */
            publish_status?: {
                [key: string]: components["schemas"]["PublishChannel"];
            };
            /** Ingredients */
            ingredients?: components["schemas"]["RecipeIngredient"][];
            /** Steps */
            steps?: string[];
            /** Nutrition */
            nutrition?: {
                [key: string]: string;
            };
            /** Tags */
            tags?: string[];
            /**
             * Hero Image Url
             * @default
             */
            hero_image_url: string;
            media?: components["schemas"]["RecipeMedia"] | null;
        };
        /**
         * RecipeIngredient
         * @description A single ingredient line from a scraped recipe.
         */
        RecipeIngredient: {
            /** Item */
            item: string;
            /**
             * Qty
             * @default
             */
            qty: string;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * RecipeMedia
         * @description On-disk media for a recipe, as BRAND_DIR-relative paths.
         *
         *     Sourced from the row's ``generated_content.media`` manifest (links only —
         *     the bytes stay on disk). The UI turns each path into a serving URL via the
         *     ``/recipes/{id}/media-file`` endpoint.
         */
        RecipeMedia: {
            /** Images */
            images?: string[];
            /** Reels */
            reels?: string[];
            /** Audio */
            audio?: string[];
            /** Featured Image */
            featured_image?: string | null;
        };
        /**
         * RecipeSummary
         * @description List-row view of a stored recipe (no ingredients/steps).
         */
        RecipeSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Artifacts Path
             * @default
             */
            artifacts_path: string;
            /**
             * Card Path
             * @default
             */
            card_path: string;
            /**
             * Card Created At
             * @default
             */
            card_created_at: string;
            /**
             * Card Html Path
             * @default
             */
            card_html_path: string;
            /**
             * Card Html Created At
             * @default
             */
            card_html_created_at: string;
            /**
             * Wp Url
             * @default
             */
            wp_url: string;
            /**
             * Ig Url
             * @default
             */
            ig_url: string;
            /**
             * Fb Url
             * @default
             */
            fb_url: string;
            /**
             * Published At
             * @default
             */
            published_at: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Dog Safe
             * @default false
             */
            dog_safe: boolean;
            /** Toxic Flags */
            toxic_flags?: string[];
            /** Season Tags */
            season_tags?: string[];
            /** Affiliate Products */
            affiliate_products?: components["schemas"]["AffiliateProduct"][];
            /**
             * Content Status
             * @default none
             */
            content_status: string;
            /** Status */
            status: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Source Name
             * @default
             */
            source_name: string;
            /**
             * Prep Minutes
             * @default 0
             */
            prep_minutes: number;
            /**
             * Cook Minutes
             * @default 0
             */
            cook_minutes: number;
            /**
             * Total Minutes
             * @default 0
             */
            total_minutes: number;
            /**
             * Servings
             * @default
             */
            servings: string;
            /** Publish Status */
            publish_status?: {
                [key: string]: components["schemas"]["PublishChannel"];
            };
        };
        /**
         * RecipesResponse
         * @description Envelope for ``GET /api/v1/recipes``.
         */
        RecipesResponse: {
            /** Recipes */
            recipes: components["schemas"]["RecipeSummary"][];
            /** Total */
            total: number;
        };
        /**
         * RejectBody
         * @description Body for ``POST /items/{id}/reject``. ``reason`` is free-form.
         */
        RejectBody: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * SeedItem
         * @description A recipe seed awaiting approval before full campaign generation.
         */
        SeedItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "seed";
            /**
             * Seed Id
             * @default
             */
            seed_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Ingredients
             * @default []
             */
            ingredients: string[];
            /** Prep Minutes */
            prep_minutes?: number | null;
            /** Cook Minutes */
            cook_minutes?: number | null;
            /**
             * Yield Servings
             * @default
             */
            yield_servings: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Dog Safety Notes
             * @default
             */
            dog_safety_notes: string;
        } & {
            [key: string]: unknown;
        };
        /** StatusBody */
        StatusBody: {
            /** Status */
            status: string;
        };
        /**
         * StatusChangeResponse
         * @description Result of an approval/rejection transition.
         */
        StatusChangeResponse: {
            /** Id */
            id: string;
            /** Content Status */
            content_status: string;
        };
        /** StatusUpdate */
        StatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "followed" | "skipped";
        };
        /**
         * SyncResponse
         * @description Result of POST /api/v1/recipes/sync-publish.
         */
        SyncResponse: {
            /** Updated */
            updated: number;
            /** Total */
            total: number;
        };
        /** TikTokCandidateItem */
        TikTokCandidateItem: {
            /** Handle */
            handle: string;
            /** Display Name */
            display_name: string;
            /** Bio */
            bio: string;
            /** Follower Count */
            follower_count: number;
            /** Source Hashtag */
            source_hashtag: string;
            /** Discovered At */
            discovered_at: string;
            /** Status */
            status: string;
        };
        /**
         * TriggerResponse
         * @description Envelope for ``POST /api/v1/schedule/{label}/trigger``.
         */
        TriggerResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Label */
            label: string;
            /** Rate Limits */
            rate_limits?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /** Label */
            label: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Last Run */
            last_run?: string | null;
            /** Message */
            message?: string | null;
            /**
             * Is Instance
             * @default false
             */
            is_instance: boolean;
            /**
             * Re Run Guard
             * @default 1
             */
            re_run_guard: number;
        };
        /** _TriggerBody */
        _TriggerBody: {
            /**
             * Count
             * @default 1
             */
            count: number;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Recipe Ids
             * @default []
             */
            recipe_ids: string[];
            /** Headless */
            headless?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
        };
    };
    get_campaign_api_v1_campaigns__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_campaign_api_v1_campaigns__name__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recipe_card_webhook_api_v1_webhooks_recipe_card_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCardWebhookPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_api_v1_recipes_get: {
        parameters: {
            query?: {
                /** @description filter by pipeline status */
                status?: string | null;
                /** @description filter by safety verdict */
                dog_safe?: boolean | null;
                /** @description filter to recipes in-season for this season */
                season?: string | null;
                /** @description filter by publish-content lifecycle state */
                content_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recipes_analytics_api_v1_recipes_analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
        };
    };
    approve_recipe_api_v1_recipes__recipe_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_recipe_api_v1_recipes__recipe_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recipe_page_api_v1_recipes__recipe_id__page_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recipe_image_preview_api_v1_recipes__recipe_id__image_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_publish_api_v1_recipes_sync_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    list_artifacts_api_v1_recipes__recipe_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_recipes__recipe_id__artifact_get: {
        parameters: {
            query: {
                /** @description path relative to the artifact folder */
                path: string;
            };
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_file_api_v1_recipes__recipe_id__media_file_get: {
        parameters: {
            query: {
                /** @description BRAND_DIR-relative media path from the manifest */
                path: string;
            };
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_card_api_v1_recipes__recipe_id__story_card_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engagements_endpoint_api_v1_engagements_get: {
        parameters: {
            query?: {
                /** @description facebook | instagram | wordpress */
                platform?: string | null;
                /** @description comment | link_post | feed_post | reel | page_post */
                kind?: string | null;
                /** @description posted | failed */
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ideas_api_v1_ideas_get: {
        parameters: {
            query?: {
                /** @description Filter by category */
                category?: string | null;
                /** @description Filter by status (default: all) */
                status?: string | null;
                /** @description Filter by brand */
                brand_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdeasResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_idea_slides_api_v1_ideas__idea_id__slides_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idea_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_idea_slide_api_v1_ideas__idea_id__slides__n__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idea_id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_idea_status_api_v1_ideas__idea_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idea_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_v1_tiktok_candidates_get: {
        parameters: {
            query?: {
                /** @description Filter by status: pending, followed, skipped */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_candidate_status_api_v1_tiktok_candidates__handle__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_pending_api_v1_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
        };
    };
    list_activity_api_v1_activity_get: {
        parameters: {
            query?: {
                limit?: number;
                platform?: ("facebook" | "instagram" | "wordpress") | null;
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentItem"] | components["schemas"]["BlogPostItem"] | components["schemas"]["GroupItem"] | components["schemas"]["IdeaItem"] | components["schemas"]["SeedItem"] | components["schemas"]["CampaignVerifyItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_item_api_v1_items__item_id__approve_post: {
        parameters: {
            query?: {
                channel?: string | null;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_item_api_v1_items__item_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RejectBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_item_api_v1_items__item_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facebook_groups_api_v1_facebook_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacebookGroupsResponse"];
                };
            };
        };
    };
    update_facebook_group_api_v1_facebook_groups__group_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacebookGroupUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacebookGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_workers_api_v1_workers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatus"][];
                };
            };
        };
    };
    worker_status_api_v1_workers__label__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_worker_api_v1_workers__label__trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["_TriggerBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missing_flows_api_v1_schedule_missing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingFlowsResponse"];
                };
            };
        };
    };
    get_schedule_log_api_v1_workers__label__log_get: {
        parameters: {
            query?: {
                lines?: number;
            };
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogTailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_artifact_api_v1_workers__label__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
