"""Pure rendering for brand onboarding — no I/O, no DB calls.

Turns onboarding-form input (`BrandSpec`) into the three artifacts a new
brand folder needs:

    render_config_json(spec)             -> AppSettings-shaped dict
    render_brand_facts_md(spec)          -> data/config/brand_facts.md text
    render_instagram_hashtags_csv(spec)  -> data/config/instagram_accounts.csv text

`persona/lib/brand_provisioning.py` is the orchestration layer that calls
these and actually writes files / DB rows. Splitting the two apart (per the
plan's PR3/B3 section) keeps this module trivially unit-testable: every
function here is a plain `spec -> str | dict` transform.

No-fabrication guarantee: `render_brand_facts_md` only ever emits verbatim
onboarding text or an explicit `<!-- TODO (owner): ... -->` placeholder for a
blank field -- never invented specifics. See `dogfoodandfun/data/config/
nalla_facts.md` for the section shape this mirrors.
"""

from __future__ import annotations

import csv
import io
from dataclasses import dataclass, field
from typing import Any

from lib.brand_template_defaults import (
    APPROVAL_GATES,
    CONTENT_ANALYSIS_DEFAULTS,
    DEDUPLICATION,
    DISABLED_CHANNEL_NOTE,
    FACEBOOK_CHANNEL_DEFAULTS,
    FILE_PATHS,
    INSTAGRAM_CHANNEL_DEFAULTS,
    RATE_LIMITS,
    VOICE_VALIDATION,
)
from lib.brands_db.models import default_enabled_flows

_DEFAULT_GROUP_JOIN_LIMIT = 10  # matches scripts/fb_group_scout.py's own fallback

_HASHTAG_CSV_HEADER = ("hashtag", "tier", "scan_frequency", "category", "notes")


@dataclass
class BrandSpec:
    """Onboarding-form input for a new brand. Every field is plain user text.

    Required: `name`, `site_url`, `niche` (mirrors `BrandsRepository.create`'s
    own required-field set). Everything else defaults to empty so a partial
    spec still renders -- blank fields become `<!-- TODO (owner) -->`
    placeholders in `render_brand_facts_md`, never invented content.
    """

    name: str
    site_url: str
    niche: str
    target_audience: str = ""
    mascot_name: str = ""
    brand_persona: str = ""
    instagram_profile_url: str = ""
    facebook_page_url: str = ""
    primary_keywords: list[str] = field(default_factory=list)
    secondary_keywords: list[str] = field(default_factory=list)
    competitor_mentions: list[str] = field(default_factory=list)
    competitor_accounts: list[str] = field(default_factory=list)
    headless: bool = True
    enabled_flows: list[str] = field(default_factory=default_enabled_flows)
    group_join_limit: int = _DEFAULT_GROUP_JOIN_LIMIT


def render_config_json(spec: BrandSpec) -> dict[str, Any]:
    """Build a complete `AppSettings`-shaped dict from onboarding input.

    `AppSettings(**render_config_json(spec))` must not raise -- that round
    trip is the regression guard in `tests/test_brand_templates.py`.
    """
    site_url = spec.site_url.rstrip("/")
    return {
        "_comment": f"{spec.name} — Persona social automation config. "
        "Generated by brand_templates.render_config_json; safe to hand-edit.",
        "_version": "1.0",
        "site": {
            "name": spec.name,
            "url": spec.site_url,
            "rss_feed": f"{site_url}/feed/",
            "sitemap": f"{site_url}/sitemap.xml",
            "brand_persona": spec.brand_persona,
            "mascot_name": spec.mascot_name,
            "niche": spec.niche,
            "target_audience": spec.target_audience,
        },
        "social_channels": {
            "facebook": {
                "enabled": True,
                "page_url": spec.facebook_page_url,
                "page_name": spec.name,
                **FACEBOOK_CHANNEL_DEFAULTS,
            },
            "instagram": {
                "enabled": True,
                "profile_url": spec.instagram_profile_url,
                **INSTAGRAM_CHANNEL_DEFAULTS,
            },
            "twitter": {"enabled": False, "profile_url": "", "note": DISABLED_CHANNEL_NOTE},
            "tiktok": {"enabled": False, "profile_url": "", "note": DISABLED_CHANNEL_NOTE},
        },
        "rate_limits": RATE_LIMITS,
        "content_analysis": {
            **CONTENT_ANALYSIS_DEFAULTS,
            # Brand-driven, always written explicitly (even empty) -- opts a
            # new brand OUT of comment_generator.py's missing-key-only
            # fallback so it never silently scores against dog-food keywords.
            "keywords": {
                "primary_keywords": list(spec.primary_keywords),
                "secondary_keywords": list(spec.secondary_keywords),
                "competitor_mentions": list(spec.competitor_mentions),
            },
            "competitor_accounts": list(spec.competitor_accounts),
        },
        "approval_gates": APPROVAL_GATES,
        "deduplication": DEDUPLICATION,
        "file_paths": FILE_PATHS,
        "voice_validation": VOICE_VALIDATION,
        # recipe_card intentionally omitted -- see brand_template_defaults.py's
        # module docstring. AppSettings.recipe_card's own Pydantic default
        # (generic, no brand-specific media id) applies.
    }


def render_brand_json(spec: BrandSpec) -> dict[str, Any]:
    """Build the `brand_dir/brand.json` runtime-overrides dict.

    `runtime.headless` is read by `lib.local_env.get_runtime_headless()`;
    `group_discovery.join_limit_per_day` is read by
    `scripts/fb_group_scout.py` (via `lib.local_env.get_group_join_limit()`)
    -- both fall back to a production-safe default when unset. Written by
    `brand_provisioning.provision_brand()` on every call (create AND
    re-provision), which is what makes a settings-page edit to either field
    actually take effect on the next scanner run.
    """
    return {
        "runtime": {"headless": spec.headless},
        "group_discovery": {"join_limit_per_day": spec.group_join_limit},
    }


def _fact_bullet(label: str, value: str, todo_hint: str) -> str:
    """One `## Who we are`/`## What we genuinely do`-style bullet.

    Verbatim `value` when supplied, else an explicit TODO comment -- never a
    fabricated value.
    """
    value = value.strip()
    if value:
        return f"- {label}: {value}"
    return f"<!-- TODO (owner): {todo_hint} -->"


def _todo_section(hint: str) -> str:
    return f"<!-- TODO (owner): {hint} -->"


def render_brand_facts_md(spec: BrandSpec) -> str:
    """Mirror `nalla_facts.md`'s section structure, generically.

    Every fact-bearing section is populated ONLY from verbatim `spec` text,
    or an explicit TODO placeholder when the owner left the field blank --
    the no-fabrication guarantee, enforced structurally. `BrandSpec` (see
    above) carries no diet/gear/anecdote fields yet, so those three sections
    are always TODO until a later onboarding step adds them -- an honest gap,
    not an invented one.
    """
    mascot = spec.mascot_name.strip() or "the mascot"
    title_subject = spec.mascot_name.strip() or spec.name.strip() or "Brand"

    lines: list[str] = [
        f"# {title_subject} Facts — ground engagement comments in these TRUE details only",
        "",
        "These are the only personal facts a drafted comment may state as ours. If a "
        "post's topic is not covered here, the comment must stay general (\"in our "
        'experience", "we\'ve noticed") and lead with a question about the other '
        "person's experience — never invent a specific.",
        "",
        "## Who we are",
        _fact_bullet(
            "Persona",
            f'"{spec.brand_persona}" — the voice behind {spec.name}.' if spec.brand_persona else "",
            "describe who runs this brand's voice/persona (e.g. \"X — a dog owner and "
            'software engineer. NOT a vet."). Until filled, comments must stay generic '
            'about who "we" are.',
        ),
        _fact_bullet(
            "Mascot",
            spec.mascot_name,
            "name the mascot (species/type, notable trait). Until filled, comments must "
            "not invent mascot details.",
        ),
        "",
        "## What we genuinely do",
        _fact_bullet(
            "Niche",
            spec.niche,
            "describe what this brand actually covers/reviews.",
        ),
        _fact_bullet(
            "We write for",
            spec.target_audience,
            "describe the target audience. Until filled, comments must stay general "
            "about who this is for.",
        ),
        "",
        '## Hard "do NOT claim" guardrails',
        f"- Do NOT claim {mascot} has any specific diet, product, or experience "
        "unless it is listed under the sections below. Until those are filled in, "
        "comments must stay general.",
        "- Do NOT invent durations, ages, weights, vet visits, or health events.",
        "- Do NOT claim we own/use a specific product unless it's listed under "
        '"Gear we actually use" below.',
        "",
        f"## {title_subject}'s diet",
        _todo_section(
            'add the true diet here, e.g. "X eats Y brand kibble with a fresh topper a '
            'few times a week." Until filled, comments must NOT assert any diet.'
        ),
        "",
        "## Gear we actually use",
        _todo_section(
            'list real products + honest take, e.g. "Fi collar — great battery, GPS '
            'struggles under dense tree cover."'
        ),
        "",
        "## Real experiences to draw on",
        _todo_section("add a few true, specific anecdotes the model can reference."),
    ]
    return "\n".join(lines) + "\n"


def _to_hashtag(keyword: str) -> str:
    """Mechanically derive a hashtag from a keyword: strip spaces, lowercase."""
    return "#" + "".join(ch for ch in keyword.lower() if ch.isalnum())


def render_instagram_hashtags_csv(spec: BrandSpec) -> str:
    """`hashtag,tier,scan_frequency,category,notes` seed, derived from keywords.

    `primary_keywords` -> tier 1 / daily; `secondary_keywords` -> tier 2 /
    every_2_days. Matches `dogfoodandfun/data/config/instagram_accounts.csv`'s
    column shape and `should_scan_today()`'s accepted `scan_frequency` values
    (`lib/engagement/adapters/instagram_parsing.py`). Header-only (no data
    rows) when no keywords are supplied -- a fresh brand's ig-scanner then
    runs cleanly and just finds nothing, per the plan's known limitations.
    """
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(_HASHTAG_CSV_HEADER)

    for kw in spec.primary_keywords:
        tag = _to_hashtag(kw)
        if tag != "#":
            writer.writerow([tag, 1, "daily", "general", "Primary keyword (auto-seeded)"])

    for kw in spec.secondary_keywords:
        tag = _to_hashtag(kw)
        if tag != "#":
            writer.writerow([tag, 2, "every_2_days", "general", "Secondary keyword (auto-seeded)"])

    return buf.getvalue()
