/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Returns the current site configuration.
         */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending
         * @description All blog-post pairs + group-join candidates awaiting a decision.
         */
        get: operations["list_pending_api_v1_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity
         * @description Tail of ``logs/engagement_log.jsonl``, most recent first.
         */
        get: operations["list_activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Look up a single item by id. 410 for legacy comments.
         */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Item
         * @description Approve an item. Dispatches on type.
         */
        post: operations["approve_item_api_v1_items__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Item
         * @description Reject an item. Dispatches on type. Logs ``body.reason`` (free-form).
         */
        post: operations["reject_item_api_v1_items__item_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Item
         * @description Approve with edited content. Only valid for blog_post items.
         */
        post: operations["edit_item_api_v1_items__item_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Facebook Groups
         * @description List all Facebook groups and their statuses.
         */
        get: operations["list_facebook_groups_api_v1_facebook_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/groups/{group_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Facebook Group
         * @description Update a Facebook group's status.
         */
        put: operations["update_facebook_group_api_v1_facebook_groups__group_name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for launchd / curl. 204 = OK, no body needed.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flows/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Flows State
         * @description Aggregate per-flow health + launchd schedule snapshot for the UI.
         */
        get: operations["get_flows_state_api_v1_flows_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/{label}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Schedule
         * @description Fire a launchd job on demand via ``launchctl start <label>``.
         *
         *     Label is whitelisted against the ``com.dogfoodandfun.*`` namespace
         *     to keep this from being abused as a generic launchctl runner. All
         *     subprocess args are list-form; no shell.
         */
        post: operations["trigger_schedule_api_v1_schedule__label__trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEntry
         * @description One row in ``logs/engagement_log.jsonl`` as exposed by ``/activity``.
         *
         *     Some legacy rows in the JSONL file use ``action="group_join_request"``;
         *     the API layer normalises those to ``"group_join"`` before constructing
         *     this model so the frontend only ever sees the canonical value. Older
         *     rows may also lack the ``date`` field — ``lib.activity_log`` derives
         *     it from ``timestamp`` so the UI can rely on both being present.
         */
        ActivityEntry: {
            /** Date */
            date: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Action
             * @enum {string}
             */
            action: "comment" | "like" | "group_post" | "reply" | "own_reply" | "page_post" | "feed_post" | "group_join" | "trace";
            /**
             * Platform
             * @enum {string}
             */
            platform: "facebook" | "instagram" | "wordpress";
            /** Target Name */
            target_name?: string | null;
            /** Target Url */
            target_url?: string | null;
            /** Content */
            content?: string | null;
            /** Reply Url */
            reply_url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ActivityResponse
         * @description Envelope for ``GET /api/v1/activity``.
         */
        ActivityResponse: {
            /** Entries */
            entries: components["schemas"]["ActivityEntry"][];
            /** Total */
            total: number;
            /** As Of */
            as_of: string;
        };
        /**
         * ApproveBody
         * @description Body for ``POST /items/{id}/approve``.
         *
         *     All fields optional: a bare approve just commits the existing draft.
         *     Pass ``text`` to override a comment, or ``fb_caption``/``ig_caption``
         *     to override a blog post pair before approval.
         */
        ApproveBody: {
            /** Text */
            text?: string | null;
            /** Fb Caption */
            fb_caption?: string | null;
            /** Ig Caption */
            ig_caption?: string | null;
        };
        /**
         * BlogPostItem
         * @description A WordPress post awaiting FB + IG caption sign-off.
         *
         *     ``channel`` is the per-platform fan-out decision set by the approver:
         *
         *     - Web UI: ``POST /items/{id}/approve?channel=fb_only`` stamps this field
         *       before flipping ``status`` to ``approved``.
         *     - Telegram: the reply parser in ``lib/notifier.py`` maps text replies
         *       (``approve``/``fb``/``ig``) onto ``"both"``/``"fb_only"``/``"ig_only"``.
         *
         *     The publisher (``scripts/content_pipeline.py::stage_publish``) reads
         *     ``channel`` after ``send_and_wait`` returns to decide which platforms to
         *     actually post to. ``None`` is valid only while the item is still pending
         *     or was skipped.
         */
        BlogPostItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "blog_post";
            /**
             * Post Title
             * @default
             */
            post_title: string;
            /**
             * Post Url
             * @default
             */
            post_url: string;
            /**
             * Post Id
             * @default 0
             */
            post_id: number;
            /**
             * Fb Caption
             * @default
             */
            fb_caption: string;
            /**
             * Ig Caption
             * @default
             */
            ig_caption: string;
            /** Image Url */
            image_url?: string | null;
            /** Channel */
            channel?: ("both" | "fb_only" | "ig_only") | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DecisionResponse
         * @description Returned on every commit endpoint.
         */
        DecisionResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /**
             * Decided By
             * @enum {string}
             */
            decided_by: "telegram" | "web_ui" | "auto";
            /** Decided At */
            decided_at: string;
            /** Join Status */
            join_status?: "queued" | null;
        };
        /**
         * EditBody
         * @description Body for ``POST /items/{id}/edit``.
         *
         *     Either ``text`` (comment items) or one/both of ``fb_caption`` /
         *     ``ig_caption`` (blog-post items) must be set — enforced in the route
         *     handler so the response is a clean 422 instead of an opaque ValidationError.
         */
        EditBody: {
            /** Text */
            text?: string | null;
            /** Fb Caption */
            fb_caption?: string | null;
            /** Ig Caption */
            ig_caption?: string | null;
        };
        /**
         * FacebookGroup
         * @description A Facebook group from groups_tracker.json.
         */
        FacebookGroup: {
            /** Group Name */
            group_name: string;
            /** Group Url */
            group_url: string;
            /** Status */
            status: string;
            /** Joined At */
            joined_at?: string | null;
            /** Rules */
            rules?: string | null;
            /** Last Post At */
            last_post_at?: string | null;
            /** Source Notification */
            source_notification?: string | null;
            /** Privacy */
            privacy?: string | null;
            /** Member Count */
            member_count?: string | null;
            /** Posting Mode */
            posting_mode?: string | null;
            /** Notes */
            notes?: {
                [key: string]: string;
            }[] | null;
            /** Last Post Status */
            last_post_status?: string | null;
            /** Last Post Caption */
            last_post_caption?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FacebookGroupUpdateBody
         * @description Body for PUT /api/v1/facebook/groups/{group_name}.
         */
        FacebookGroupUpdateBody: {
            /** Status */
            status?: string | null;
            /** Posting Mode */
            posting_mode?: string | null;
        };
        /**
         * FacebookGroupsResponse
         * @description Envelope for GET /api/v1/facebook/groups.
         */
        FacebookGroupsResponse: {
            /** Groups */
            groups: components["schemas"]["FacebookGroup"][];
            /** Total */
            total: number;
            /** As Of */
            as_of: string;
        };
        /**
         * FlowState
         * @description One row in the ``/flows/state`` response — health snapshot of a flow.
         *
         *     Six top-level flows surface to the UI: engagement-comment, blog-campaign,
         *     community-growth, social-loyalty, market-intel, content-ideas. Each
         *     reader assembles its own ``output_counts`` shape (keys vary per flow);
         *     the UI renders them generically. ``sample`` is a small (≤3) tail of the
         *     most recent items the flow produced, redacted of any token/secret/
         *     password/cookie/auth-keyed fields before serialisation.
         */
        FlowState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Last Run At */
            last_run_at?: string | null;
            /**
             * Last Status
             * @enum {string}
             */
            last_status: "ok" | "error" | "never" | "stale" | "manual";
            /** Error Message */
            error_message?: string | null;
            /** Output Counts */
            output_counts: {
                [key: string]: number;
            };
            /** Sample */
            sample: {
                [key: string]: unknown;
            }[];
        };
        /**
         * FlowsStateResponse
         * @description Envelope for ``GET /api/v1/flows/state``.
         */
        FlowsStateResponse: {
            /** Flows */
            flows: components["schemas"]["FlowState"][];
            /** Schedule */
            schedule: components["schemas"]["ScheduleEntry"][];
        };
        /**
         * GroupItem
         * @description A Facebook group surfaced by ``fb_group_scout`` awaiting a join
         *     decision.
         *
         *     Producer side (``lib/group_discovery/state.py:add_to_pending``) writes
         *     the discovery payload without ``id``/``status``/``decided_by`` — the API
         *     layer synthesises those when reading (see ``lib/groups_queue.py``). The
         *     ``model_config = extra="allow"`` inherited from ``_ItemBase`` keeps the
         *     extra producer fields (``post_frequency``, ``competitor_names``,
         *     ``description``) intact for the UI even though they aren't declared.
         */
        GroupItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group_to_join";
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Member Count */
            member_count?: number | null;
            /** Score */
            score?: number | null;
            /** Privacy */
            privacy?: ("public" | "private") | null;
            /** Found Via Query */
            found_via_query?: string | null;
            /** Competitor Mentions */
            competitor_mentions?: number | null;
            /** Added To Pending */
            added_to_pending: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PendingResponse
         * @description Envelope for ``GET /api/v1/pending``.
         */
        PendingResponse: {
            /** Items */
            items: (components["schemas"]["BlogPostItem"] | components["schemas"]["GroupItem"])[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** As Of */
            as_of: string;
        };
        /**
         * RejectBody
         * @description Body for ``POST /items/{id}/reject``. ``reason`` is free-form.
         */
        RejectBody: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * ScheduleEntry
         * @description One launchd job in the ``/flows/state`` schedule list.
         *
         *     Sourced from ``launchctl list`` + ``~/Library/LaunchAgents/com.<brand>.*``
         *     plist files. ``is_loaded`` is True iff the label currently appears in
         *     ``launchctl list`` output. ``last_exit_code`` is the second column from
         *     launchctl (parsed int, or None when not loaded / waiting). ``flow_id``
         *     maps the cron label back to the parent flow when one exists, else None.
         */
        ScheduleEntry: {
            /** Label */
            label: string;
            /** Flow Id */
            flow_id?: string | null;
            /** Schedule Human */
            schedule_human: string;
            /** Last Fire At */
            last_fire_at?: string | null;
            /** Last Exit Code */
            last_exit_code?: number | null;
            /** Is Loaded */
            is_loaded: boolean;
            /** Order */
            order?: number | null;
            /** Depends On */
            depends_on?: string[];
            /** Inputs Satisfied */
            inputs_satisfied?: boolean;
            /** Input Status */
            input_status?: components["schemas"]["InputStatus"][];
        };
        /**
         * InputStatus
         * @description One declared input prerequisite for a scheduled task.
         */
        InputStatus: {
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
            /** Count */
            count: number;
            /** Age Hours */
            age_hours: number | null;
            /** Ok */
            ok: boolean;
            /** Reason */
            reason: string | null;
        };
        /**
         * TriggerResponse
         * @description Envelope for ``POST /api/v1/schedule/{label}/trigger``.
         */
        TriggerResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_pending_api_v1_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
        };
    };
    list_activity_api_v1_activity_get: {
        parameters: {
            query?: {
                limit?: number;
                platform?: ("facebook" | "instagram" | "wordpress") | null;
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostItem"] | components["schemas"]["GroupItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_item_api_v1_items__item_id__approve_post: {
        parameters: {
            query?: {
                channel?: string | null;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_item_api_v1_items__item_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RejectBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_item_api_v1_items__item_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facebook_groups_api_v1_facebook_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacebookGroupsResponse"];
                };
            };
        };
    };
    update_facebook_group_api_v1_facebook_groups__group_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacebookGroupUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacebookGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_flows_state_api_v1_flows_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowsStateResponse"];
                };
            };
        };
    };
    trigger_schedule_api_v1_schedule__label__trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}

// ----------------------------------------------------------------------
// Manual type aliases (re-appended after openapi-typescript regen).
// Mirrors the original hand-rolled tail; keep in sync with backend.
// ----------------------------------------------------------------------
export type ActivityAction = components["schemas"]["ActivityEntry"]["action"];
export type ActivityEntry = components["schemas"]["ActivityEntry"];
export type ActivityResponse = components["schemas"]["ActivityResponse"];
export type Platform = components["schemas"]["ActivityEntry"]["platform"];
export type BlogPostItem = components["schemas"]["BlogPostItem"];
export type GroupItem = components["schemas"]["GroupItem"];
export type PendingItem = BlogPostItem | GroupItem;
export type PendingResponse = components["schemas"]["PendingResponse"];
export type Channel = components["schemas"]["BlogPostItem"]["channel"];
export type DecisionResponse = components["schemas"]["DecisionResponse"];
// Fallback for CommentItem
export type CommentItem = {
    id: string;
    type: "comment";
    platform: Platform;
    group_or_hashtag?: string;
    post_url?: string;
    post_text: string;
    draft_comment: string;
    relevance_score?: number;
    status: string;
    decided_by?: "telegram" | "web_ui" | "auto" | null;
    decided_at?: string | null;
    created_at?: string | null;
};
export type FacebookGroup = components["schemas"]["FacebookGroup"];
export type FacebookGroupsResponse = components["schemas"]["FacebookGroupsResponse"];
export type FacebookGroupUpdateBody = components["schemas"]["FacebookGroupUpdateBody"];

// ----------------------------------------------------------------------
// Hand-written types — backend exposes these but openapi.json hasn't
// been regenerated yet. Mirror the pydantic models in api/schemas.py.
// ----------------------------------------------------------------------
export interface LogTailResponse {
    label: string;
    path: string | null;
    lines: string[];
    truncated: boolean;
}

export interface MissingFlowEntry {
    label: string;
    plist_path: string | null;
    command: string;
}

export interface MissingFlowsResponse {
    missing: MissingFlowEntry[];
    as_of: string;
}

/** Extension of components["schemas"]["ScheduleEntry"] with fields not yet
 *  reflected in openapi.json. Backend already returns these per the
 *  Phase-6 server changes. */
export type ScheduleEntry = components["schemas"]["ScheduleEntry"] & {
    script_path?: string | null;
    log_path?: string | null;
    output_file?: string | null;
};

export type InputStatus = components["schemas"]["InputStatus"];
