/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campaigns
         * @description Return one summary per folder under campaigns_dir that has a config.
         *
         *     Folders without ``campaign_config.json`` are silently skipped — the
         *     UI only renders runnable campaigns. Invalid configs are also skipped
         *     (logged at WARN) so a single broken JSON file can't 500 the list.
         */
        get: operations["list_campaigns_api_v1_campaigns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Campaign
         * @description Return full detail (summary + history) for a single campaign.
         */
        get: operations["get_campaign_api_v1_campaigns__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{name}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Campaign
         * @description Spawn ``scripts.publish_campaign`` as a detached subprocess.
         *
         *     Fire-and-forget by design: the publisher writes to ``state.json`` and
         *     the frontend polls ``GET /campaigns``. Lock conflicts surface there
         *     as ``last_status="error"`` on the next poll, identical to the cron
         *     path. Returns immediately with the spawned PID.
         */
        post: operations["publish_campaign_api_v1_campaigns__name__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/recipe-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recipe Card Webhook
         * @description Accept a WordPress publish event and queue PDF generation.
         */
        post: operations["recipe_card_webhook_api_v1_webhooks_recipe_card_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recipes
         * @description List stored recipes (alphabetical) with optional filters.
         */
        get: operations["list_recipes_api_v1_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recipe
         * @description Full detail for one recipe, including ingredients and steps.
         */
        get: operations["get_recipe_api_v1_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/sync-publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Publish
         * @description Refresh each recipe's publish status from the publish records.
         *
         *     Reads the brand's ``campaigns/**\/metadata.json`` and
         *     ``published_recipes.json`` and writes per-channel status onto matching
         *     recipe rows. Idempotent and safe to call repeatedly.
         */
        post: operations["sync_publish_api_v1_recipes_sync_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Returns the current site configuration.
         */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending
         * @description All blog-post pairs, group-join candidates, ideas, seeds, campaign-verify items, and comments awaiting a decision.
         */
        get: operations["list_pending_api_v1_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity
         * @description Tail of ``logs/engagement_log.jsonl``, most recent first.
         */
        get: operations["list_activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Look up a single item by id.
         */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Item
         * @description Approve an item. Dispatches on type.
         */
        post: operations["approve_item_api_v1_items__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Item
         * @description Reject an item. Dispatches on type. Logs ``body.reason`` (free-form).
         */
        post: operations["reject_item_api_v1_items__item_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Item
         * @description Approve with edited content. Only valid for blog_post items.
         */
        post: operations["edit_item_api_v1_items__item_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Facebook Groups
         * @description List all Facebook groups bucketed by status.
         *
         *     Merges two sources:
         *       - groups_tracker.json -> status in {joined, join_requested, rejected}
         *       - pending_groups.json -> projected with synthetic status="not_joined_yet"
         */
        get: operations["list_facebook_groups_api_v1_facebook_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facebook/groups/{group_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Facebook Group
         * @description Update a Facebook group's status.
         */
        put: operations["update_facebook_group_api_v1_facebook_groups__group_name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for launchd / curl. 204 = OK, no body needed.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flows/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Flows State
         * @description Aggregate per-flow health + launchd schedule snapshot for the UI.
         */
        get: operations["get_flows_state_api_v1_flows_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flows/guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Flows Guide
         * @description Static flow descriptions merged with live last-run state.
         */
        get: operations["get_flows_guide_api_v1_flows_guide_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/{label}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Schedule
         * @description Fire a launchd job on demand via ``launchctl start <label>``.
         *
         *     Label is whitelisted against the ``com.dogfoodandfun.*`` namespace
         *     to keep this from being abused as a generic launchctl runner. All
         *     subprocess args are list-form; no shell. Unless ``force=true`` is
         *     passed, the task's declared inputs in ``schedule.json`` must be
         *     fresh -- failing a precondition short-circuits with a 200 body
         *     carrying ``ok=False`` and the human-readable reason.
         */
        post: operations["trigger_schedule_api_v1_schedule__label__trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Missing Flows
         * @description Return scheduled flows defined in schedule.json that aren't loaded in launchctl.
         */
        get: operations["list_missing_flows_api_v1_schedule_missing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/{label}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Log
         * @description Return the last N lines of the log file for a scheduled job.
         *
         *     Label is whitelisted against the ``com.dogfoodandfun.*`` namespace.
         *     Log path is read from the matching plist's ``StandardOutPath`` —
         *     never user-supplied — so we cannot be coerced into reading arbitrary
         *     files via path traversal.
         */
        get: operations["get_schedule_log_api_v1_schedule__label__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/{label}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Artifact
         * @description Return the JSON content of the output_file for a scheduled job.
         *
         *     Securely reads only files declared in schedule.json as output_file.
         */
        get: operations["get_schedule_artifact_api_v1_schedule__label__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEntry
         * @description One row in ``logs/engagement_log.jsonl`` as exposed by ``/activity``.
         *
         *     Some legacy rows in the JSONL file use ``action="group_join_request"``;
         *     the API layer normalises those to ``"group_join"`` before constructing
         *     this model so the frontend only ever sees the canonical value. Older
         *     rows may also lack the ``date`` field — ``lib.activity_log`` derives
         *     it from ``timestamp`` so the UI can rely on both being present.
         */
        ActivityEntry: {
            /** Date */
            date: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Action
             * @enum {string}
             */
            action: "comment" | "like" | "group_post" | "reply" | "own_reply" | "page_post" | "feed_post" | "group_join" | "trace";
            /**
             * Platform
             * @enum {string}
             */
            platform: "facebook" | "instagram" | "wordpress" | "system";
            /** Target Name */
            target_name?: string | null;
            /** Target Url */
            target_url?: string | null;
            /** Content */
            content?: string | null;
            /** Reply Url */
            reply_url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ActivityResponse
         * @description Envelope for ``GET /api/v1/activity``.
         */
        ActivityResponse: {
            /** Entries */
            entries: components["schemas"]["ActivityEntry"][];
            /** Total */
            total: number;
            /** As Of */
            as_of: string;
        };
        /**
         * ApproveBody
         * @description Body for ``POST /items/{id}/approve``.
         *
         *     All fields optional: a bare approve just commits the existing draft.
         *     Pass ``text`` to override a comment, or ``fb_caption``/``ig_caption``
         *     to override a blog post pair before approval.
         */
        ApproveBody: {
            /** Text */
            text?: string | null;
            /** Fb Caption */
            fb_caption?: string | null;
            /** Ig Caption */
            ig_caption?: string | null;
        };
        /**
         * BlogPostItem
         * @description A WordPress post awaiting FB + IG caption sign-off.
         *
         *     ``channel`` is the per-platform fan-out decision set by the approver:
         *
         *     - Web UI: ``POST /items/{id}/approve?channel=fb_only`` stamps this field
         *       before flipping ``status`` to ``approved``.
         *     - Telegram: the reply parser in ``lib/notifier.py`` maps text replies
         *       (``approve``/``fb``/``ig``) onto ``"both"``/``"fb_only"``/``"ig_only"``.
         *
         *     The publisher (``scripts/content_pipeline.py::stage_publish``) reads
         *     ``channel`` after ``send_and_wait`` returns to decide which platforms to
         *     actually post to. ``None`` is valid only while the item is still pending
         *     or was skipped.
         */
        BlogPostItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "blog_post";
            /**
             * Post Title
             * @default
             */
            post_title: string;
            /**
             * Post Url
             * @default
             */
            post_url: string;
            /**
             * Post Id
             * @default 0
             */
            post_id: number;
            /**
             * Fb Caption
             * @default
             */
            fb_caption: string;
            /**
             * Ig Caption
             * @default
             */
            ig_caption: string;
            /** Image Url */
            image_url?: string | null;
            /** Channel */
            channel?: ("both" | "fb_only" | "ig_only") | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CampaignDetail
         * @description Detail payload for ``GET /api/v1/campaigns/{name}``.
         *
         *     Extends ``CampaignSummary`` with the full run history list so the UI
         *     can render the timeline view without a second round-trip.
         */
        CampaignDetail: {
            /** Name */
            name: string;
            /** Last Run */
            last_run?: string | null;
            /**
             * Current Task Index
             * @default 0
             */
            current_task_index: number;
            /**
             * Last Status
             * @default never
             * @enum {string}
             */
            last_status: "success" | "error" | "never";
            /**
             * Ready Count
             * @default 0
             */
            ready_count: number;
            /**
             * Published Count
             * @default 0
             */
            published_count: number;
            /**
             * Has Prepare Tasks
             * @default false
             */
            has_prepare_tasks: boolean;
            /**
             * Has Publish Tasks
             * @default false
             */
            has_publish_tasks: boolean;
            /**
             * History
             * @default []
             */
            history: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CampaignListResponse
         * @description Envelope for ``GET /api/v1/campaigns``.
         */
        CampaignListResponse: {
            /** Campaigns */
            campaigns: components["schemas"]["CampaignSummary"][];
        };
        /**
         * CampaignSummary
         * @description Summary row for ``GET /api/v1/campaigns``.
         *
         *     Aggregates the on-disk campaign config + state.json + ready/published
         *     folder counts into a single UI-friendly shape. ``last_status`` is
         *     derived from ``state.history[-1].status`` and defaults to ``"never"``
         *     when the campaign has no run history yet.
         */
        CampaignSummary: {
            /** Name */
            name: string;
            /** Last Run */
            last_run?: string | null;
            /**
             * Current Task Index
             * @default 0
             */
            current_task_index: number;
            /**
             * Last Status
             * @default never
             * @enum {string}
             */
            last_status: "success" | "error" | "never";
            /**
             * Ready Count
             * @default 0
             */
            ready_count: number;
            /**
             * Published Count
             * @default 0
             */
            published_count: number;
            /**
             * Has Prepare Tasks
             * @default false
             */
            has_prepare_tasks: boolean;
            /**
             * Has Publish Tasks
             * @default false
             */
            has_publish_tasks: boolean;
        };
        /**
         * CampaignVerifyItem
         * @description A campaign awaiting final human verification before publish.
         */
        CampaignVerifyItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "campaign_verify";
            /**
             * Seed Id
             * @default
             */
            seed_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Wp Draft Url
             * @default
             */
            wp_draft_url: string;
            /** Audio Size Kb */
            audio_size_kb?: number | null;
            /** Slide Count */
            slide_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CommentItem
         * @description A Facebook / Instagram / WordPress engagement comment.
         *
         *     Legacy schema — engagement comments no longer flow through the web UI,
         *     but the model is retained so the autonomous pipeline (comment_poster)
         *     and legacy items in ``comment_queue.json`` can still validate.
         */
        CommentItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "comment";
            /**
             * Platform
             * @enum {string}
             */
            platform: "facebook" | "instagram" | "wordpress" | "system";
            /** Group Or Hashtag */
            group_or_hashtag?: string | null;
            /** Post Url */
            post_url?: string | null;
            /**
             * Post Text
             * @default
             */
            post_text: string;
            /**
             * Draft Comment
             * @default
             */
            draft_comment: string;
            /** Relevance Score */
            relevance_score?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DecisionResponse
         * @description Returned on every commit endpoint.
         */
        DecisionResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /**
             * Decided By
             * @enum {string}
             */
            decided_by: "telegram" | "web_ui" | "auto";
            /** Decided At */
            decided_at: string;
            /** Join Status */
            join_status?: "queued" | null;
        };
        /**
         * EditBody
         * @description Body for ``POST /items/{id}/edit``.
         *
         *     Either ``text`` (comment items) or one/both of ``fb_caption`` /
         *     ``ig_caption`` (blog-post items) must be set — enforced in the route
         *     handler so the response is a clean 422 instead of an opaque ValidationError.
         */
        EditBody: {
            /** Text */
            text?: string | null;
            /** Fb Caption */
            fb_caption?: string | null;
            /** Ig Caption */
            ig_caption?: string | null;
        };
        /**
         * FacebookGroup
         * @description A Facebook group from groups_tracker.json.
         */
        FacebookGroup: {
            /** Group Name */
            group_name: string;
            /** Group Url */
            group_url: string;
            /** Status */
            status: string;
            /** Joined At */
            joined_at?: string | null;
            /** Rules */
            rules?: string | null;
            /** Last Post At */
            last_post_at?: string | null;
            /** Source Notification */
            source_notification?: string | null;
            /** Privacy */
            privacy?: string | null;
            /** Member Count */
            member_count?: string | null;
            /** Posting Mode */
            posting_mode?: string | null;
            /** Notes */
            notes?: {
                [key: string]: string;
            }[] | null;
            /** Last Post Status */
            last_post_status?: string | null;
            /** Last Post Caption */
            last_post_caption?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FacebookGroupUpdateBody
         * @description Body for PUT /api/v1/facebook/groups/{group_name}.
         */
        FacebookGroupUpdateBody: {
            /** Status */
            status?: string | null;
            /** Posting Mode */
            posting_mode?: string | null;
        };
        /**
         * FacebookGroupsResponse
         * @description Envelope for GET /api/v1/facebook/groups.
         */
        FacebookGroupsResponse: {
            /** Groups */
            groups: components["schemas"]["FacebookGroup"][];
            /** Total */
            total: number;
            /** As Of */
            as_of: string;
        };
        /**
         * FlowGuideEntry
         * @description A flow description merged with its live last-run state.
         */
        FlowGuideEntry: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Jobs
             * @default []
             */
            jobs: components["schemas"]["JobDescription"][];
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Status */
            last_status?: string | null;
        };
        /**
         * FlowGuideResponse
         * @description Response shape for ``GET /api/v1/flows/guide``.
         */
        FlowGuideResponse: {
            /** Flows */
            flows: components["schemas"]["FlowGuideEntry"][];
        };
        /**
         * FlowState
         * @description One row in the ``/flows/state`` response — health snapshot of a flow.
         *
         *     Six top-level flows surface to the UI: engagement-comment, blog-campaign,
         *     community-growth, social-loyalty, market-intel, content-ideas. Each
         *     reader assembles its own ``output_counts`` shape (keys vary per flow);
         *     the UI renders them generically. ``sample`` is a small (≤3) tail of the
         *     most recent items the flow produced, redacted of any token/secret/
         *     password/cookie/auth-keyed fields before serialisation.
         */
        FlowState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Last Run At */
            last_run_at?: string | null;
            /**
             * Last Status
             * @enum {string}
             */
            last_status: "ok" | "error" | "never" | "stale" | "manual";
            /** Error Message */
            error_message?: string | null;
            /** Output Counts */
            output_counts: {
                [key: string]: number;
            };
            /** Sample */
            sample: {
                [key: string]: unknown;
            }[];
        };
        /**
         * FlowsStateResponse
         * @description Envelope for ``GET /api/v1/flows/state``.
         */
        FlowsStateResponse: {
            /** Flows */
            flows: components["schemas"]["FlowState"][];
            /** Schedule */
            schedule: components["schemas"]["ScheduleEntry"][];
        };
        /**
         * GroupItem
         * @description A Facebook group surfaced by ``fb_group_scout`` awaiting a join
         *     decision.
         *
         *     Producer side (``lib/group_discovery/state.py:add_to_pending``) writes
         *     the discovery payload without ``id``/``status``/``decided_by`` — the API
         *     layer synthesises those when reading (see ``lib/groups_queue.py``). The
         *     ``model_config = extra="allow"`` inherited from ``_ItemBase`` keeps the
         *     extra producer fields (``post_frequency``, ``competitor_names``,
         *     ``description``) intact for the UI even though they aren't declared.
         */
        GroupItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group_to_join";
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Member Count */
            member_count?: number | null;
            /** Score */
            score?: number | null;
            /** Privacy */
            privacy?: ("public" | "private") | null;
            /** Found Via Query */
            found_via_query?: string | null;
            /** Competitor Mentions */
            competitor_mentions?: number | null;
            /** Added To Pending */
            added_to_pending: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdeaItem
         * @description A recipe/content idea from the ideator queue awaiting approval.
         */
        IdeaItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "idea";
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Why Now
             * @default
             */
            why_now: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /** Seasonal Relevance */
            seasonal_relevance?: number | null;
            /**
             * Search Demand Estimate
             * @default
             */
            search_demand_estimate: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputStatus
         * @description Per-input freshness check result for a scheduled task.
         *
         *     Emitted by ``check_inputs_satisfied`` in ``api.schedule_config``. The
         *     ``ok`` flag is the AND of the existence, count, and age checks. A
         *     failed check writes a human-readable ``reason`` so the UI can render
         *     it as a tooltip without re-running the check client-side.
         */
        InputStatus: {
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
            /** Count */
            count: number;
            /** Age Hours */
            age_hours: number | null;
            /** Ok */
            ok: boolean;
            /** Reason */
            reason?: string | null;
        };
        /**
         * JobDescription
         * @description One-liner describing a single cron job inside a flow.
         */
        JobDescription: {
            /** Id */
            id: string;
            /** Summary */
            summary: string;
            /** Category */
            category?: string | null;
        };
        /**
         * LogTailResponse
         * @description Envelope for ``GET /api/v1/schedule/{label}/log``.
         */
        LogTailResponse: {
            /** Label */
            label: string;
            /** Path */
            path: string | null;
            /** Lines */
            lines: string[];
            /** Truncated */
            truncated: boolean;
        };
        /**
         * MissingFlowEntry
         * @description One scheduled flow that's defined in schedule.json but not loaded in launchctl.
         */
        MissingFlowEntry: {
            /** Label */
            label: string;
            /** Plist Path */
            plist_path?: string | null;
            /** Command */
            command: string;
        };
        /**
         * MissingFlowsResponse
         * @description Envelope for ``GET /api/v1/schedule/missing``.
         */
        MissingFlowsResponse: {
            /** Missing */
            missing: components["schemas"]["MissingFlowEntry"][];
            /** As Of */
            as_of: string;
        };
        /**
         * PendingResponse
         * @description Envelope for ``GET /api/v1/pending``.
         */
        PendingResponse: {
            /** Items */
            items: (components["schemas"]["CommentItem"] | components["schemas"]["BlogPostItem"] | components["schemas"]["GroupItem"] | components["schemas"]["IdeaItem"] | components["schemas"]["SeedItem"] | components["schemas"]["CampaignVerifyItem"])[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** As Of */
            as_of: string;
        };
        /**
         * PublishChannel
         * @description Publish state for one channel (wp / pdf / ig / fb).
         *
         *     IG-only extras (``caption`` / ``reel_url`` / ``post_url``) carry the
         *     Instagram single-image post + reel split surfaced in the UI popup. They
         *     stay empty for the other channels.
         */
        PublishChannel: {
            /**
             * State
             * @default
             */
            state: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Ref
             * @default
             */
            ref: string;
            /**
             * At
             * @default
             */
            at: string;
            /**
             * Caption
             * @default
             */
            caption: string;
            /**
             * Reel Url
             * @default
             */
            reel_url: string;
            /**
             * Post Url
             * @default
             */
            post_url: string;
        };
        /** RecipeCardWebhookPayload */
        RecipeCardWebhookPayload: {
            /** Post Id */
            post_id: number;
            /** Post Status */
            post_status: string;
            /**
             * Post Type
             * @default post
             */
            post_type: string;
        };
        /**
         * RecipeDetail
         * @description Full recipe payload for ``GET /api/v1/recipes/{id}``.
         */
        RecipeDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Artifacts Path
             * @default
             */
            artifacts_path: string;
            /**
             * Wp Url
             * @default
             */
            wp_url: string;
            /**
             * Ig Url
             * @default
             */
            ig_url: string;
            /**
             * Fb Url
             * @default
             */
            fb_url: string;
            /**
             * Published At
             * @default
             */
            published_at: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Dog Safe
             * @default false
             */
            dog_safe: boolean;
            /** Toxic Flags */
            toxic_flags?: string[];
            /** Status */
            status: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Source Name
             * @default
             */
            source_name: string;
            /**
             * Prep Minutes
             * @default 0
             */
            prep_minutes: number;
            /**
             * Cook Minutes
             * @default 0
             */
            cook_minutes: number;
            /**
             * Total Minutes
             * @default 0
             */
            total_minutes: number;
            /**
             * Servings
             * @default
             */
            servings: string;
            /** Publish Status */
            publish_status?: {
                [key: string]: components["schemas"]["PublishChannel"];
            };
            /** Ingredients */
            ingredients?: components["schemas"]["RecipeIngredient"][];
            /** Steps */
            steps?: string[];
            /** Nutrition */
            nutrition?: {
                [key: string]: string;
            };
            /** Tags */
            tags?: string[];
            /**
             * Hero Image Url
             * @default
             */
            hero_image_url: string;
        };
        /**
         * RecipeIngredient
         * @description A single ingredient line from a scraped recipe.
         */
        RecipeIngredient: {
            /** Item */
            item: string;
            /**
             * Qty
             * @default
             */
            qty: string;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * RecipeSummary
         * @description List-row view of a stored recipe (no ingredients/steps).
         */
        RecipeSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Artifacts Path
             * @default
             */
            artifacts_path: string;
            /**
             * Wp Url
             * @default
             */
            wp_url: string;
            /**
             * Ig Url
             * @default
             */
            ig_url: string;
            /**
             * Fb Url
             * @default
             */
            fb_url: string;
            /**
             * Published At
             * @default
             */
            published_at: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Dog Safe
             * @default false
             */
            dog_safe: boolean;
            /** Toxic Flags */
            toxic_flags?: string[];
            /** Status */
            status: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Source Name
             * @default
             */
            source_name: string;
            /**
             * Prep Minutes
             * @default 0
             */
            prep_minutes: number;
            /**
             * Cook Minutes
             * @default 0
             */
            cook_minutes: number;
            /**
             * Total Minutes
             * @default 0
             */
            total_minutes: number;
            /**
             * Servings
             * @default
             */
            servings: string;
            /** Publish Status */
            publish_status?: {
                [key: string]: components["schemas"]["PublishChannel"];
            };
        };
        /**
         * RecipesResponse
         * @description Envelope for ``GET /api/v1/recipes``.
         */
        RecipesResponse: {
            /** Recipes */
            recipes: components["schemas"]["RecipeSummary"][];
            /** Total */
            total: number;
        };
        /**
         * RejectBody
         * @description Body for ``POST /items/{id}/reject``. ``reason`` is free-form.
         */
        RejectBody: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * ScheduleEntry
         * @description One launchd job in the ``/flows/state`` schedule list.
         *
         *     Sourced from ``launchctl list`` + ``~/Library/LaunchAgents/com.<brand>.*``
         *     plist files. ``is_loaded`` is True iff the label currently appears in
         *     ``launchctl list`` output. ``last_exit_code`` is the second column from
         *     launchctl (parsed int, or None when not loaded / waiting). ``flow_id``
         *     maps the cron label back to the parent flow when one exists, else None.
         */
        ScheduleEntry: {
            /** Label */
            label: string;
            /** Flow Id */
            flow_id?: string | null;
            /** Schedule Human */
            schedule_human: string;
            /** Last Fire At */
            last_fire_at?: string | null;
            /** Last Exit Code */
            last_exit_code?: number | null;
            /** Script Path */
            script_path?: string | null;
            /** Log Path */
            log_path?: string | null;
            /** Is Loaded */
            is_loaded: boolean;
            /** Order */
            order?: number | null;
            /** Output File */
            output_file?: string | null;
            /** Depends On */
            depends_on?: string[];
            /**
             * Inputs Satisfied
             * @default true
             */
            inputs_satisfied: boolean;
            /** Input Status */
            input_status?: components["schemas"]["InputStatus"][];
        };
        /**
         * SeedItem
         * @description A recipe seed awaiting approval before full campaign generation.
         */
        SeedItem: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Decided By */
            decided_by?: ("telegram" | "web_ui" | "auto") | null;
            /** Decided At */
            decided_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "seed";
            /**
             * Seed Id
             * @default
             */
            seed_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Ingredients
             * @default []
             */
            ingredients: string[];
            /** Prep Minutes */
            prep_minutes?: number | null;
            /** Cook Minutes */
            cook_minutes?: number | null;
            /**
             * Yield Servings
             * @default
             */
            yield_servings: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Dog Safety Notes
             * @default
             */
            dog_safety_notes: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SyncResponse
         * @description Result of POST /api/v1/recipes/sync-publish.
         */
        SyncResponse: {
            /** Updated */
            updated: number;
            /** Total */
            total: number;
        };
        /**
         * TriggerResponse
         * @description Envelope for ``POST /api/v1/schedule/{label}/trigger``.
         */
        TriggerResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
        };
    };
    get_campaign_api_v1_campaigns__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_campaign_api_v1_campaigns__name__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recipe_card_webhook_api_v1_webhooks_recipe_card_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCardWebhookPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_api_v1_recipes_get: {
        parameters: {
            query?: {
                /** @description filter by pipeline status */
                status?: string | null;
                /** @description filter by safety verdict */
                dog_safe?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_publish_api_v1_recipes_sync_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_pending_api_v1_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
        };
    };
    list_activity_api_v1_activity_get: {
        parameters: {
            query?: {
                limit?: number;
                platform?: ("facebook" | "instagram" | "wordpress") | null;
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentItem"] | components["schemas"]["BlogPostItem"] | components["schemas"]["GroupItem"] | components["schemas"]["IdeaItem"] | components["schemas"]["SeedItem"] | components["schemas"]["CampaignVerifyItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_item_api_v1_items__item_id__approve_post: {
        parameters: {
            query?: {
                channel?: string | null;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_item_api_v1_items__item_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RejectBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_item_api_v1_items__item_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facebook_groups_api_v1_facebook_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacebookGroupsResponse"];
                };
            };
        };
    };
    update_facebook_group_api_v1_facebook_groups__group_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacebookGroupUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacebookGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_flows_state_api_v1_flows_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowsStateResponse"];
                };
            };
        };
    };
    get_flows_guide_api_v1_flows_guide_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowGuideResponse"];
                };
            };
        };
    };
    trigger_schedule_api_v1_schedule__label__trigger_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missing_flows_api_v1_schedule_missing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingFlowsResponse"];
                };
            };
        };
    };
    get_schedule_log_api_v1_schedule__label__log_get: {
        parameters: {
            query?: {
                lines?: number;
            };
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogTailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_artifact_api_v1_schedule__label__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
